name    'desalvo-libvirt'
version '0.1.1'
source 'https://github.com/desalvo/puppet-libvirt'
author 'desalvo'
license 'Apache License, Version 2.0'
summary 'Puppet module for libvirt management'
description 'A puppet module for managing libvirt configurations'
project_page 'https://github.com/desalvo/puppet-libvirt'
